import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";

import CoffeeShop from "../components/CoffeeShop/CoffeeShop";
import styles from "../styles/Home.module.css";
import { CoffeeShopsType } from "../types";

const Home: NextPage = () => {
	const [data, setData] = useState([]);

	useEffect(() => {
		axios({
			method: "GET",
			url: "api/coffeeshop",
		}).then((response) => {
			setData(response.data);
		});
	}, []);

	// if (error) return <div>Failed to load</div>;
	// if (!data) return <div>Loading...</div>;

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Near Me</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<ul className={styles.coffeeshops}>
					{data &&
						data.map((coffeeshop: CoffeeShopsType) => (
							<CoffeeShop key={coffeeshop.id} {...coffeeshop} />
						))}
				</ul>
			</main>
		</div>
	);
};

export default Home;
