import type { NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";

import CoffeeShop from "../components/CoffeeShop/CoffeeShop";
import styles from "../styles/Home.module.css";

import { CoffeeShopsType } from "../types";

const fetcher = (url: RequestInfo) => fetch(url).then((res) => res.json());

const Home: NextPage = () => {
	const { data, error } = useSWR("api/coffeeshop", fetcher);

	if (error) return <div>Failed to load</div>;
	if (!data) return <div>Loading...</div>;

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Near Me</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<ul className={styles.coffeeshops}>
					{data.map((coffeeshop: CoffeeShopsType, index: number) => (
						<CoffeeShop key={index} {...coffeeshop} />
					))}
				</ul>
			</main>
		</div>
	);
};

export default Home;
